apiVersion: apps/v1
kind: Deployment
metadata:
  name: appav
spec:
  selector:
    matchLabels:
      app: appav
  replicas: 3
  template:
    metadata:
      labels:
        app: appav
    spec:
      containers:
      - name: appav
        image: atharv
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
